apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-project
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/prithvirajkc/Devtron-meetup.git # URL of the Git repo
    targetRevision: HEAD
    path: yaml_files # Directory inside the repo
  destination: 
    server: https://kubernetes.default.svc # Target cluster (Service name in default ns)
    namespace: devtron

  syncPolicy:
    syncOptions:
    - CreateNamespace=true #Creates if namespace is not present

    automated:
      selfHeal: true 
      prune: false
