apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-project
  namespace: argocd
spec:
  project: argocd-proj

  source:
    repoURL: https://github.com/prithvirajkc/Devtron-meetup.git
    targetRevision: HEAD

  destination: 
    server: https://kubernetes.default.svc
    namespace: devtron

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
