apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-project
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/prithvirajkc/Devtron-meetup.git # URL of the Git repo
    targetRevision: HEAD
    path: yaml_files # Directory inside the repo
  destination: 
    server: https://kubernetes.default.svc # Target cluster (Service name in default ns)
    namespace: devtron

  syncPolicy:
    syncOptions:
    - CreateNamespace=true #Creates if namespace is not present

    automated:
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      prune: false #Specifies if resources should be pruned during auto-syncing ( false by default ).
